news/urls.py
# -*- coding: utf-8 -*-
"""
URL Configuration.
"""
from django.conf.urls import url, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

from news.viewsets import TopicViewSet, SegmentViewSet, ChannelAudienceViewSet

router = DefaultRouter()
router.register(r'topic', TopicViewSet)
router.register(r'segment', SegmentViewSet)
router.register(r'channel_audience', ChannelAudienceViewSet)

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='news/home.html'), name='home'),
    url(r'^topic_by_channel/?$', TemplateView.as_view(template_name='news/topic_by_channel.html'),
        name='topic_by_channel'),
    url(r'^topic_performance/?$', TemplateView.as_view(template_name='news/topic_performance.html'),
        name='topic_performance'),
    url(r'^topic_best_segments/?$', TemplateView.as_view(template_name='news/topic_best_segments.html'),
        name='topic_best_segments'),
    url(r'^api/', include(router.urls, namespace='v1')),
]

news_challenge/urls.py
# -*- coding: utf-8 -*-
"""
URL Configuration
"""
from django.conf.urls import include, url
from django.contrib import admin

import news.urls

urlpatterns = [
    url(r'^backend/', include(admin.site.urls)),
    url(r'^news/', include(news.urls, namespace='news')),
]

news/models.py
"""
News models.
"""
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _

from django_pandas.managers import DataFrameManager


class Channel(models.Model):
    """
    Represents a Channel.
    """
    name = models.CharField(_('name'), max_length=200)

    def __str__(self):
        return self.name

    def __repr__(self):
        return "Channel{%s}" % (self.name, )


class ChannelAudience(models.Model):
    """
    Represents audience in a channel.
    """
    timestamp = models.DateTimeField(_('timestamp'))
    audience = models.BigIntegerField(_('audience'))
    channel = models.ForeignKey(Channel, verbose_name=_('channel'))

    # Change default manager to easy use pandas DataFrame
    objects = DataFrameManager()

    def __str__(self):
        return "%s (%s)" % (self.audience, str(self.timestamp))

    def __repr__(self):
        return "ChannelAudience{%s, %s, %s}" % (self.channel, self.audience, str(self.timestamp))


class Segment(models.Model):
    """
    Represents a segment.
    """
    start = models.DateTimeField(_('start timestamp'))
    end = models.DateTimeField(_('end timestamp'))
    channel = models.ForeignKey(Channel, verbose_name=_('channel'))

    # Change default manager to easy use pandas DataFrame
    objects = DataFrameManager()

    def __str__(self):
        return "[%s - %s]" % (str(self.start), str(self.end))

    def __repr__(self):
        return "Segment{%s, %s, %s}" % (repr(self.channel), str(self.start), str(self.end))


class Topic(models.Model):
    """
    Represents a topic with:

    * Name: Name of the topic.
    * Count: Number of time the topic was mentioned in the segment.
    * Score: Higher means the topic is more relevant to the segment.
    """
    name = models.CharField(_('name'), max_length=1000)
    count = models.IntegerField(_('count'))
    score = models.FloatField(_('score'))
    segment = models.ForeignKey(Segment, verbose_name=_('segment'))

    # Change default manager to easy use pandas DataFrame
    objects = DataFrameManager()

    def __str__(self):
        return self.name

    def __repr__(self):
        return "Topic{%s, %d, %.2f}" % (self.name, self.count, self.score)

news/views.py
# -*- coding: utf-8 -*-

news/templates/news/base/base.html
{% load compress %}
{% load staticfiles %}

<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{% block page_title %}{{ _("News Challenge") }}{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}Website for News Challenge app{% endblock %}">
  <meta name="author" content="{% block meta_author %}PeRDy{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {% block meta %}
  {% endblock %}

  {# use the CDN to get bootstrap css. can not be inside compress css block #}
  {% block cdn_css %}
    <!-- Material Design fonts -->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">

    <!-- Bootstrap -->
    <link rel="stylesheet"
          href="https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/dist/dist/bootstrap-material-design.min.css">
  {% endblock cdn_css %}

  {% compress css %}
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    {% block css %}{% endblock %}
  {% endcompress %}
</head>
<body class="{% block body_class %}{% endblock %}" {% block body_attributes %}{% endblock %}>
{% block body %}
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->
  <header>
    {% block header %}{% endblock %}
  </header>

  <div class="container" role="main">
    {% block content %}{% endblock %}
  </div>

  <footer>
    {% block footer %}
    {% endblock footer %}
  </footer>


  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  {% block cdn_js %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <script type="text/javascript" src="https://cdn.rawgit.com/HubSpot/tether/v1.3.2/dist/js/tether.min.js"></script>
    <script type="text/javascript"
            src="https://cdn.rawgit.com/fezvrasta/bootstrap-material-design/dist/dist/bootstrap-material-design.iife.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.3.3/backbone-min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/backbone.marionette/2.5.6/backbone.marionette.min.js"></script>
  {% endblock cdn_js %}

  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src=""></script>

  <!-- Init bootstrap material design -->
  <script>
    $('body').bootstrapMaterialDesign()
  </script>

  <!-- scripts concatenated and minified via django-compressor -->
  {% compress js %}
    <script src="{% static 'js/main.js' %}"></script>
    {% block js %}{% endblock js %}
    <script src="{% static 'js/start.js' %}"></script>
  {% endcompress %}
  <!-- end scripts -->
{% endblock %}
</body>
</html>

news/templates/news/home.html
{% extends "news/base/base.html" %}

{% block header %}
  <nav class="navbar navbar-light bg-faded">
    <a class="navbar-brand" href="{% url "news:home" %}">News</a>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url "news:topic_by_channel" %}">Topics By Channel</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "news:topic_performance" %}">Topic Performance</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "news:topic_best_segments" %}">Best Segments</a>
      </li>
    </ul>
  </nav>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-4">
      <div class="card card-block">
        <h4 class="card-title">Topics by Channel</h4>
        <p class="card-text">Shows topics with best audience depending on channels.</p>
        <a class="card-link" href="{% url "news:topic_by_channel" %}">Go to page</a>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card card-block">
        <h4 class="card-title">Topic Performance</h4>
        <p class="card-text">Shows performance of a topic in all channels.</p>
        <a class="card-link" href="{% url "news:topic_performance" %}">Go to page</a>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card card-block">
        <h4 class="card-title">Topic Best Segments</h4>
        <p class="card-text">Shows segments with best audience for a topic.</p>
        <a class="card-link" href="{% url "news:topic_best_segments" %}">Go to page</a>
      </div>
    </div>
  </div>
{% endblock %}

news/templates/news/items/no_items.html
<div class="card card-block">
  <h4 class="card-title">Empty results</h4>
  <p class="card-text">No items found</p>
</div>

news/templates/news/items/performance.html
<% var performance_formatted = (audience * 100).toFixed(2) + '%'; %>

<div class="card card-block">
  <h4 class="card-title">Performance</h4>
  <ul class="list-group bmd-list-group-sm list-group-flush">
    <li class="list-group-item">
      <div class="bmd-list-group-col">
        <p class="list-group-item-heading">Channel</p>
        <p class="list-group-item-text"><%= channel %></p>
      </div>
    </li>
    <li class="list-group-item">
      <div class="bmd-list-group-col">
        <p class="list-group-item-heading">Performance</p>
        <p class="list-group-item-text"><%= performance_formatted %></p>
      </div>
    </li>
  </ul>
</div>

news/templates/news/items/segment.html
<%
var start_date = new Date(start);
var end_date = new Date(end);
var start_formatted = start_date.toUTCString();
var end_formatted = end_date.toUTCString();
%>

<div class="card card-block">
  <h4 class="card-title">Segment</h4>
  <ul class="list-group bmd-list-group-sm list-group-flush">
    <li class="list-group-item">
      <div class="bmd-list-group-col">
        <p class="list-group-item-heading">Channel</p>
        <p class="list-group-item-text"><%= channel %></p>
      </div>
    </li>
    <li class="list-group-item">
      <div class="bmd-list-group-col">
        <p class="list-group-item-heading">Start</p>
        <p class="list-group-item-text"><%= start_formatted %></p>
      </div>
    </li>
    <li class="list-group-item">
      <div class="bmd-list-group-col">
        <p class="list-group-item-heading">End</p>
        <p class="list-group-item-text"><%= end_formatted %></p>
      </div>
    </li>
  </ul>
</div>

news/templates/news/items/topics_in_channel.html
<div class="card card-block">
  <h4 class="card-title">Channel <%= name %></h4>
  <ul class="list-group bmd-list-group-sm">
    <% _.each(topics, function(topic){ %>
    <li class="list-group-item"><%= topic %></li>
    <% }); %>
  </ul>
</div>

news/templates/news/topic_best_segments.html
{% extends "news/base/base.html" %}
{% load staticfiles %}

{% block header %}
  <nav class="navbar navbar-light bg-faded">
    <a class="navbar-brand" href="{% url "news:home" %}">News</a>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url "news:topic_by_channel" %}">Topics By Channel</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "news:topic_performance" %}">Topic Performance</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url "news:topic_best_segments" %}">Best Segments</a>
      </li>
    </ul>
  </nav>
{% endblock %}

{% block content %}
  <div id="topic-best-segments-view">
    <div id="collection"></div>

    <script type="text/template" id="composite-view-template">
      <div class="row">
        <div class="col-xs-12">
          <div class="card card-block">
            <form class="form">
              <fieldset class="form-group" id="topic-name-group">
                <label for="topic-name" class="bmd-label-floating">Topic name</label>
                <input class="form-control" type="text" id="topic-name">
              </fieldset>
              <fieldset class="form-group">
                <button type="submit" class="btn btn-primary has-spinner">
                  <span class="spinner"><i class="material-icons material-icons-spin">autorenew</i></span>
                  Submit
                </button>
              </fieldset>
            </form>
          </div>
        </div>
      </div>

      <div class="row hidden-xs-up" id="segments-collection"></div>
    </script>

    <script type="text/template" id="segment-template">{% include "news/items/segment.html" %}</script>
    <script type="text/template" id="empty-template">{% include "news/items/no_items.html" %}</script>
  </div>

{% endblock %}

{% block js %}
  <script src="{% static 'js/topics_best_segments.js' %}"></script>
{% endblock %}

news/templates/news/topic_by_channel.html
{% extends "news/base/base.html" %}
{% load staticfiles %}

{% block header %}
  <nav class="navbar navbar-light bg-faded">
    <a class="navbar-brand" href="{% url "news:home" %}">News</a>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "news:topic_by_channel" %}">Topics By Channel</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "news:topic_performance" %}">Topic Performance</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "news:topic_best_segments" %}">Best Segments</a>
      </li>
    </ul>
  </nav>
{% endblock %}

{% block content %}
  <div id="topic-by-channel-view">
    <div id="collection"></div>

    <script type="text/template" id="composite-view-template">
      <div class="row">
        <div class="col-xs-12">
          <div class="card card-block">
            <form class="form">
              <fieldset class="form-group" id="topic-date-group">
                <label for="topic-date" class="bmd-label-floating">Date</label>
                <input class="form-control" type="date" id="topic-date">
                <span class="bmd-help">Format: MM/DD/YYYY</span>
              </fieldset>
              <fieldset class="form-group">
                <button type="submit" class="btn btn-primary has-spinner">
                  <span class="spinner"><i class="material-icons material-icons-spin">autorenew</i></span>
                  Submit
                </button>
              </fieldset>
            </form>
          </div>
        </div>
      </div>

      <div class="row hidden-xs-up" id="channels-collection"></div>
    </script>

    <script type="text/template" id="channel-template">{% include "news/items/topics_in_channel.html" %}</script>
    <script type="text/template" id="empty-template">{% include "news/items/no_items.html" %}</script>
  </div>

{% endblock %}

{% block js %}
  <script src="{% static 'js/topics_by_channel.js' %}"></script>
{% endblock %}

news/templates/news/topic_performance.html
{% extends "news/base/base.html" %}
{% load staticfiles %}

{% block header %}
  <nav class="navbar navbar-light bg-faded">
    <a class="navbar-brand" href="{% url "news:home" %}">News</a>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url "news:topic_by_channel" %}">Topics By Channel</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url "news:topic_performance" %}">Topic Performance</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "news:topic_best_segments" %}">Best Segments</a>
      </li>
    </ul>
  </nav>
{% endblock %}

{% block content %}
  <div id="topic-performance-view">
    <div id="collection"></div>

    <script type="text/template" id="composite-view-template">
      <div class="row">
        <div class="col-xs-12">
          <div class="card card-block">
            <form class="form">
              <fieldset class="form-group" id="topic-name-group">
                <label for="topic-name" class="bmd-label-floating">Topic name</label>
                <input class="form-control" type="text" id="topic-name">
              </fieldset>
              <fieldset class="form-group">
                <button type="submit" class="btn btn-primary has-spinner">
                  <span class="spinner"><i class="material-icons material-icons-spin">autorenew</i></span>
                  Submit
                </button>
              </fieldset>
            </form>
          </div>
        </div>
      </div>

      <div class="row hidden-xs-up" id="performances-collection"></div>
    </script>

    <script type="text/template" id="performance-template">{% include "news/items/performance.html" %}</script>
    <script type="text/template" id="empty-template">{% include "news/items/no_items.html" %}</script>
  </div>

{% endblock %}

{% block js %}
  <script src="{% static 'js/topics_performance.js' %}"></script>
{% endblock %}